### ISSUE TITLE
有没有可能出个一键启动

### ISSUE THREAD

**Issue by qhq** [leecobaby/shortcuts#1]
可以运行一个捷径就逐个运行金币，天猫，农场这些脚本。这样晚上睡觉前打开挂上跑他个一小时。早上起来就可以了。

**Comment by xingliuchao** [comment]
启动什么？？

**Comment by leecobaby** [comment]
> 可以运行一个捷径就逐个运行金币，天猫，农场这些脚本。这样晚上睡觉前打开挂上跑他个一小时。早上起来就可以了。

已经出了 AutoBox 就有你说的这种功能
https://github.com/leecobaby/shortcuts/AutoBox
