### ISSUE TITLE
一直停留在快捷指令界面 没有打开淘宝

### ISSUE THREAD

**Issue by petterEat** [leecobaby/shortcuts#10]
如题

**Comment by leecobaby** [comment]
尝试重启手机，重装指令试试，只兼容ios13-14------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年6月3日(星期四) 中午11:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[leecobaby/shortcuts] 一直停留在快捷指令界面 没有打开淘宝 (#10)

**Comment by petterEat** [comment]
最新的14.6，重启 重装都试过了 停留在出现的版本号的那个通知界面 然后就不动了
![image](https://user-images.githubusercontent.com/16751387/120600961-f081ec00-c47b-11eb-94d1-752ddb776bbe.png)

**Comment by petterEat** [comment]
我傻了 要点开始任务是吧  哈哈哈 打扰了

**Comment by petterEat** [comment]
do it
