### ISSUE TITLE
最新的互助合伙是自动提交吗？

### ISSUE THREAD

**Issue by charleyyy** [leecobaby/shortcuts#12]
最新的互助合伙是自动提交吗？还是我的时间到了可以自动随机找人

**Comment by leecobaby** [comment]
> 最新的互助合伙是自动提交吗？还是我的时间到了可以自动随机找人

需要手动参与的，还做不到自动

**Comment by charleyyy** [comment]
> > 最新的互助合伙是自动提交吗？还是我的时间到了可以自动随机找人
> 
> 需要手动参与的，还做不到自动

感谢大佬~~
