### ISSUE TITLE
京东 动物联盟

### ISSUE THREAD

**Issue by YuDi0-0** [leecobaby/shortcuts#15]
京东 动物联盟，图鉴任务和加购物车任务，显示转换错误（设定变量失败，因为快捷指令无法将文本转换为词典）

**Comment by leecobaby** [comment]
> 京东 动物联盟，图鉴任务和加购物车任务，显示转换错误（设定变量失败，因为快捷指令无法将文本转换为词典）

反馈很详细 正在解决这个问题 ，大概晚上可结束此 issus

**Comment by YuDi0-0** [comment]
大概下午的时候，除了图鉴以外的问题都解决了，可以正常运行。
晚上出现了新的问题：
做任务《...》等待完成
－－→ｏｎｅＡｃｔｉｖｉｔｙＩｎｆｏ９任务失败，此接口失效等待修复


另提供一种新的获取cookie思路
https://wwe.lanzoui.com/b01obgcje     
密码:52pj
此软件中扫码登录30天方式获取的cookie，从ｃｏｎｆｉｇ文件提取出来实测登录可用
（由于不方便收验证码被迫使用了这种方式）

虽然不比ｓｃｒｉｐｔａｂｌｅ跳转京东授权方便，但如果能将此方法单独提炼为【扫码－－获取ｃｏｏｋｉｅ至剪贴板／ｔｘｔ文件】，在手动获取ｃｏｏｋｉｅ方面应该也能优化不少

**Comment by leecobaby** [comment]
> 大概下午的时候，除了图鉴以外的问题都解决了，可以正常运行。
> 
> 晚上出现了新的问题：
> 
> 做任务《...》等待完成
> 
> －－→ｏｎｅＡｃｔｉｖｉｔｙＩｎｆｏ９任务失败，此接口失效等待修复
> 
> 
> 
> 
> 
> 另提供一种新的获取cookie思路
> 
> https://wwe.lanzoui.com/b01obgcje     
> 
> 密码:52pj
> 
> 此软件中扫码登录30天方式获取的cookie，从ｃｏｎｆｉｇ文件提取出来实测登录可用
> 
> （由于不方便收验证码被迫使用了这种方式）
> 
> 
> 
> 虽然不比ｓｃｒｉｐｔａｂｌｅ跳转京东授权方便，但如果能将此方法单独提炼为【扫码－－获取ｃｏｏｋｉｅ至剪贴板／ｔｘｔ文件】，在手动获取ｃｏｏｋｉｅ方面应该也能优化不少


这种非开源软件具有一定的风险，我也在尝试脱离scriptable 利用快捷指令原生组件实现优雅的跳转授权 这样能向下兼容ios13， 9 这个接口还有待观察，不同人是不同的表现
