### ISSUE TITLE
京东的任务，能有脚本吗

### ISSUE THREAD

**Issue by chenshijielt** [leecobaby/shortcuts#2]

**Comment by leecobaby** [comment]
> _No description provided._

可以的

**Comment by chenshijielt** [comment]
给个链接



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Leeco <notifications@github.com&gt;
发送时间: 2021年1月21日 21:54
收件人: leecobaby/shortcuts <shortcuts@noreply.github.com&gt;
抄送: chenshijielt <823967102@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2)





  
No description provided.
  
可以的

**Comment by leecobaby** [comment]
> 给个链接 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Leeco <notifications@github.com&gt; 发送时间: 2021年1月21日 21:54 收件人: leecobaby/shortcuts <shortcuts@noreply.github.com&gt; 抄送: chenshijielt <823967102@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2) No description provided. 可以的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://github.com/leecobaby/shortcuts/tree/master/JD_nian

**Comment by chenshijielt** [comment]
收到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Leeco <notifications@github.com&gt;
发送时间: 2021年1月21日 21:58
收件人: leecobaby/shortcuts <shortcuts@noreply.github.com&gt;
抄送: chenshijielt <823967102@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2)





  
给个链接 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Leeco <notifications@github.com&gt; 发送时间: 2021年1月21日 21:54 收件人: leecobaby/shortcuts <shortcuts@noreply.github.com&gt; 抄送: chenshijielt <823967102@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2) No description provided. 可以的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
https://github.com/leecobaby/shortcuts/tree/master/JD_nian

**Comment by chenshijielt** [comment]
在“”中，找不到词典键“data”的值'


这是什么原因
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leecobaby/shortcuts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 晚上9:58
收件人:&nbsp;"leecobaby/shortcuts"<shortcuts@noreply.github.com&gt;;
抄送:&nbsp;"ｃｓｊ"<823967102@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2)





  
给个链接 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: Leeco <notifications@github.com&gt; 发送时间: 2021年1月21日 21:54 收件人: leecobaby/shortcuts <shortcuts@noreply.github.com&gt; 抄送: chenshijielt <823967102@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[leecobaby/shortcuts] 京东的任务，能有脚本吗 (#2) No description provided. 可以的 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
https://github.com/leecobaby/shortcuts/tree/master/JD_nian

**Comment by linyali888** [comment]
淘宝里的试用，U先试用能做个脚本吗？
