### ISSUE TITLE
淘宝的脚本同一个店铺已经不能薅羊毛了

### ISSUE THREAD

**Issue by semsdawn** [leecobaby/shortcuts#23]
一直薅兰蔻的羊毛现在一个店铺貌似只可以领一次奖励了，那个15次店铺的浏览一轮运行下来完成情况是0/15，一次奖励也没有领导，希望能更新一下   :)

**Comment by leecobaby** [comment]
> 一直薅兰蔻的羊毛现在一个店铺貌似只可以领一次奖励了，那个15次店铺的浏览一轮运行下来完成情况是0/15，一次奖励也没有领导，希望能更新一下 :)

已经更新 ，选择最后一个选项，运行指令

**Comment by SeemsDawn** [comment]
只做最后一个任务，显示最后更新时间也是今天，但是仍然只薅兰蔻的羊毛

**Comment by leecobaby** [comment]
> 只做最后一个任务，显示最后更新时间也是今天，但是仍然只薅兰蔻的羊毛

这跟兰蔻没有半毛关系，只是利于我快速维护而已，如果你任务全都做完了，等明天运行吧。
