### ISSUE TITLE
转换错误！如果失败，因为快捷指令无法将文本转换成词典！（求助）

### ISSUE THREAD

**Issue by xjd008** [leecobaby/shortcuts#30]
我3个账号，就一个账号没问题！全部都是手动输入cookie（pt_key+pt_pin），另外二个账号就是弹这个转换错误！无法继续运行！请问这是啥原因？
最后谢谢大佬持续更新~~祝大佬发大财！

**Comment by xjd008** [comment]
还有就是手动做任务都可以！都没问题！

**Comment by leecobaby** [comment]
﻿13.3和越狱系统容易出问题，其他系统尝试重启手机过重装指令

发自我的iPhone



发自我的iPhone

**Comment by xjd008** [comment]
我手机14.6版本（无越狱），重启也是没效果！悲剧啊~~就那个账号抓得cookie能用其他都是转换词典失败！

**Comment by leecobaby** [comment]
多尝试，很可能是cookie错误或过期，特别是JSON为空的


发自我的iPhone
