### ISSUE TITLE
无法获取喵糖，一直跳转到薅猫毛学院界面

### ISSUE THREAD

**Issue by DerekYam** [leecobaby/shortcuts#31]
![5af0b3c34cb2ffcfe8b454a7085347d](https://user-images.githubusercontent.com/41607037/140276033-eea4e65e-cf65-4758-83f3-e7ec41781dc9.png)

**Comment by leecobaby** [comment]
﻿
﻿
﻿你这是10点的，我已经修复了，你再试试

发自我的iPhone



发自我的iPhone

**Comment by leecobaby** [comment]
﻿
﻿
﻿
﻿你这是10点的，我已经修复了，你再试试

发自我的iPhone



发自我的iPhone

**Comment by DerekYam** [comment]
> ﻿ ﻿ ﻿你这是10点的，我已经修复了，你再试试 发自我的iPhone 发自我的iPhone
> […](#)
> 在 2021年11月4日，15:48，DerekYam ***@***.***> 写道： ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

刚刚试了，确实好了，谢谢
