### ISSUE TITLE
芭芭农场自动集肥料用不了

### ISSUE THREAD

**Issue by BurniGRay** [leecobaby/shortcuts#33]
如图，点芭芭农场自动集肥料打开的是全民寻宝，然后这个捷径也打不开
![B1625784-6A3D-4476-A773-281AAC423156](https://user-images.githubusercontent.com/80145862/140403874-361dfa07-3ea0-4fc2-b7bd-ddf9250b174e.png)
![C0BC0A31-D652-4365-AC1B-FE47EA130079](https://user-images.githubusercontent.com/80145862/140403883-ee3d6bcf-d3ed-4a31-b32a-178ae9a2227f.png)

**Comment by leecobaby** [comment]
你点的就是全民寻宝

**Comment by BurniGRay** [comment]
我点的真是芭芭农场，我录了屏

Uploading IMG_2250.MP4…

**Comment by BurniGRay** [comment]
> 你点的就是全民寻宝

我录了屏，点的真是芭芭农场

https://user-images.githubusercontent.com/80145862/140543809-9cedfcca-1775-4dce-94e2-c6a7b2add16c.mov

**Comment by leecobaby** [comment]
嗯主页的链接放错了，已改正~
