### ISSUE TITLE
steam证书安好了，抓包开启进safari无法打开其他网页，进微信淘宝app没问题

### ISSUE THREAD

**Issue by heathmistry** [leecobaby/shortcuts#36]
![0D671560-A3BD-46E6-802D-C2FCDC7A2CE9](https://user-images.githubusercontent.com/44107202/143729403-719bfc57-4bfa-4633-a184-251cebc8cbe1.png)
safari所有网页都打不开，提示这个错误，感觉像是steam抓包证书有问题吗？

但是进淘宝app 微信都能正常访问

**Comment by leecobaby** [comment]
﻿
﻿需要信任CA证书和信任描述文件两步，请仔细看教程和Stream教程。

发自我的iPhone



发自我的iPhone

**Comment by heathmistry** [comment]
确实，steam教程分了两步，其实有添加vpn 信任描述文件 信任CA证书三个，漏了一步，感谢
