### ISSUE TITLE
芭芭农场快捷指令显示未找到，无法找到捷径

### ISSUE THREAD

**Issue by wg5945** [leecobaby/shortcuts#38]
https://www.icloud.com/shortcuts/79e1a54ff3d949c9994e778b3a6a2620

这个链接打不开了，显示未找到，无法找到捷径

**Comment by leecobaby** [comment]
> https://www.icloud.com/shortcuts/79e1a54ff3d949c9994e778b3a6a2620
> 
> 
> 
> 这个链接打不开了，显示未找到，无法找到捷径

Apple网络的问题，过段时间再试
