### ISSUE TITLE
芭芭农场显示无法评估键路径

### ISSUE THREAD

**Issue by wg5945** [leecobaby/shortcuts#40]
芭芭农场显示无法评估键路径
![WechatIMG236](https://user-images.githubusercontent.com/5310295/160225869-beed8742-73ce-49a3-88b0-eff80a00bc15.jpeg)

**Comment by leecobaby** [comment]
将会逐步更新指令版本，那时会将关闭此问题

**Comment by pcicp** [comment]
京东-东东农场 https://github.com/leecobaby/shortcuts/tree/master/JD_fruit 也有这问题

**Comment by leecobaby** [comment]
已解决此问题
