### ISSUE TITLE
一直助力失败是什么回事？

### ISSUE THREAD

**Issue by alex-cham** [leecobaby/shortcuts#42]
![微信图片_20220526132749](https://user-images.githubusercontent.com/34160079/170422655-a8fd8d1b-838d-441a-a94d-6a914640ee57.jpg)
其他运行正常。

**Comment by alex-cham** [comment]
![20220526134221](https://user-images.githubusercontent.com/34160079/170424212-057c0553-c75f-4a26-959d-25786801cb4f.jpg)
这是log提供的信息。

**Comment by leecobaby** [comment]
官方限制了
