### ISSUE TITLE
单独的京东京豆类签到捷径

### ISSUE THREAD

**Issue by Queen-004** [leecobaby/shortcuts#44]
希望能有一个单独的京东京豆签到的捷径，
目前的多合一签到为什么会有618活动的信息，，不是专门有618的捷径吗~

**Comment by leecobaby** [comment]
> 希望能有一个单独的京东京豆签到的捷径， 目前的多合一签到为什么会有618活动的信息，，不是专门有618的捷径吗~

多合一签到，会尝试加入更多京豆类任务，光靠一个签到是没多少豆的，部分京豆活动是现实的，比如618，而炸年兽，农场，萌宠，都是会单独做指令的。
