### ISSUE TITLE
无法评估键路径

### ISSUE THREAD

**Issue by luketse7z** [leecobaby/shortcuts#5]
在“data”中，找不到词典键“result”的值。

**Comment by leecobaby** [comment]
填入的Cookie是错误的，请仔细审查是否抓错了Cookie的值，不要把‘Cookie:’和不相干的内容也填入进去，确保本体内容的正确性

**Comment by JWAutumn** [comment]
我也出现了类似的问题。昨天还行，今天就提示这个。换了cookie也不行
