### ISSUE TITLE
现在兰蔻页面不出金币时间进度

### ISSUE THREAD

**Issue by lanmuz** [leecobaby/shortcuts#7]
其他页面有逛15s收金币的进度条.兰蔻的没有.而且哪怕都跑完任务也没完成.

**Comment by leecobaby** [comment]
> 其他页面有逛15s收金币的进度条.兰蔻的没有.而且哪怕都跑完任务也没完成.

哪个指令，重启手机试试，目前没有问题应该

**Comment by leeviok** [comment]
我现在也是，一直在兰蔻和快捷指令之间相互跳转，好像进到了死循环，重启了一次手机还是那样😭

**Comment by leeviok** [comment]
是不是由于我是晚上十一点多执行的，到十二点没有执行完，然后任务刷新了导致的

**Comment by iamxpy** [comment]
6.7 测试天猫 618 自动养猫，经常提示 “任务异常，请返回重试~”，这是预期之中的吗，因为也有收到提示 “任务已经全部完成啦”

**Comment by leecobaby** [comment]
此问题 重启手机，拒绝上一次任务即可解决
