### ISSUE TITLE
手动搞了一周，今天终于用到了，谢谢作者55

### ISSUE THREAD

**Issue by Maks111111** [leecobaby/shortcuts#9]
手动搞了一周，搞着搞着总是睡着了，没搞完，谢谢作者大大，另外不知廉耻的问一句有jd618的吗55555

**Comment by leecobaby** [comment]
> 手动搞了一周，搞着搞着总是睡着了，没搞完，谢谢作者大大，另外不知廉耻的问一句有jd618的吗55555

收到，已在做~

**Comment by Maks111111** [comment]
starstar5555
